services:
  - type: web
    name: flask-app
    env: python
    pythonVersion: "3.12"
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    plan: free
    region: oregon
